### ISSUE TITLE
support for just html files

### ISSUE THREAD

**Issue by sethburtonhall** [fruitstudios/Craft-Twig#1]
file types are listed as`.twig` & `html.twig` - is there any chance just `.html` can be supported?

**Comment by sethburtonhall** [comment]
any progress on this? Thanks.

**Comment by shornuk** [comment]
Apologies, forgot about this one! I'm not sure we'll add the `html filetype to this one.
I'm assuming you'd like it so that it automatically chooses the Craft (Twig) syntax for`html`files by default? 
If so, I believe this is now possible via a user setting called`core.customFileTypes`
It was introduced in 1.08 [See here](https://github.com/atom/atom/releases/tag/v1.0.8)
I've not used it myself, but more discussion on it can be read [here](https://github.com/atom/atom/issues/1718)

**Comment by sethburtonhall** [comment]
Yes, that is in core, although I am trying to work out the syntax. Right now I have this, but I am unsure whether to write `twig` or `Twig` or `.twig`

```
  core:
    customFileTypes:
      "source.html": [
        "twig"
      ]
```

**Comment by shornuk** [comment]
`craft-twig` should do it.
Let me know how you get on.

**Comment by sethburtonhall** [comment]
Here is my code in `config.cson`

```
"*":
  core:
    customFileTypes:
      "source.html": [
        "craft-twig"
      ]
```

but I am actually unsure of the expected behavior. As of now, I open an `.html` file but `craft-twig` snippets don't work. I would like to now open an `.html` file and have the craft-twig snippets work.

**Comment by shornuk** [comment]
Looks right. From what I understand that should default html files to open with the Craft syntax. I'm afraid I don't have a working installation on this machine at the moment. As soon as I've tested I'll let you know.

**Comment by sethburtonhall** [comment]
Thanks @shornuk.

**Comment by shornuk** [comment]
Just had a play at getting this to work in the config and it doesn't seem to be working. Looking at that thread it appears many people are having issues.
I still don't want to add the html in as a default as I think it's a bit to opinionated. The best workaround I can suggest is that you got to the installed packaged > view code and then just add `html` to the filetypes.

```
fileTypes: [
"twig"
"html.twig"
"html"
]
```

This will obviously be removed if the package is updated but it's a minor tweak to make to tailor it to your needs.
Cheers.

**Comment by sethburtonhall** [comment]
Thanks for the hack, although it still doesn't work. When I open up and html file, the syntax is `.html` not `.twig` and the craft-twig snippets do not work, unless I change syntax to `.twig`.

What I really want is the syntax to be `.html` and the craft-twig snippets to work within that syntax.

**Comment by sethburtonhall** [comment]
correction: changing the syntax to HTML(twig) does the trick. `.html` syntax with working snippets.

Thanks
