### ISSUE TITLE
}} Tag not working correctly

### ISSUE THREAD

**Issue by Chrisedmo** [fruitstudios/Craft-Twig#2]
Hey - love this plugin. However I'm having a few weird issues:

If i use the %% then tab, I get the following:

```
{%  %}{% end %}
```

with two cursors in both brackets.

**Comment by shornuk** [comment]
Sorry, just seen this. I'll have a look.

**Comment by shornuk** [comment]
Hi, 

Just check this. I cannot seem to replicate it. I'm getting the expected behaviour.
