### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by darylknight** [fruitstudios/Craft-Twig#3]
Hiya, I'm trying to get all my HTML files to open using the `Craft (Twig)` syntax, but I can't get it working correctly. The following in `config.cson` doesn't work:

```
customFileTypes:
    "source.html": [
        "html-twig"
    ]
```

`craft`, `twig` and `craft-twig` also don't work. Can you let me know what's correct please? Thanks!

**Comment by samhibberd** [comment]
@shornuk decided not to include this by default although it can be activated manually.

Go to Settings -Packages - craft-twig - Settings and View Code
Open craft-twig/grammars/craft-twig.cson and modify the filetypes setting:

`
fileTypes: [
  "twig"
  "html.twig"
  "html"
]
`

Not sure if we can add this as an option, will investigate.

**Comment by darylknight** [comment]
Thanks for your reply Sam. It's also possible to configure this in config.cson:

`"text.html.twig": [
        "html"
      ]`

Credit to Carl Seelbach for finding that.

**Comment by samhibberd** [comment]
Probably better to do it globally!
