### ISSUE TITLE
Craft (Twig) vs. Jekyll (HTML)

### ISSUE THREAD

**Issue by heymarkreeves** [fruitstudios/Craft-Twig#5]
I have the Jekyll-Atom package installed in Atom as well, which includes syntax support for Jekyll (Liquid) templates. That shows up in the syntax list as `Jekyll (HTML)`.

Any chance of optimizing Craft-Twig to better differentiate templates? I'm not sure where the issue lies, but whenever I open a Craft template, including one I've previously worked with, it defaults to `Jekyll (HTML)` and I have to switch it to `Craft (Twig)` before syntax highlighting or comment shortcuts work properly.

If there's something I can configure, I'm happy to do so as well.

Thanks!

**Comment by shornuk** [comment]
Hi, you can set which filetype to associate within the grammers file. See this thread. https://github.com/fruitstudios/Craft-Twig/issues/7
