### ISSUE TITLE
Auto Detect File Syntax?

### ISSUE THREAD

**Issue by yohoGDES** [fruitstudios/Craft-Twig#7]
Is there a way to set Atom to auto detect Craft (Twig) files within the Craft folder? Currently whenever I open a file I have to assign the syntax in order to get proper highlighting. While I know I can hit ctrl + shift + l and type "craft" - having it do this automatically would be wonderful.

Any help here would be hugely appreciated.

**Comment by jan-dh** [comment]
+1, atm it's very frustrating to manually change the file type every time you open a craft template file.

**Comment by ben-callaway** [comment]
Hello,

I'm out of the office on annual leave, back Monday 12th December.

For all enquiries, please don’t hesitate to get in touch with the team on 01962 809 103 or

Sam Hibberd
sam@fruitstudios.co.uk

Sean Hill
sean@fruitstudios.co.uk

Sam Corney
samc@fruitstudios.co.uk

Thank you.

Kind regards,
Ben Callaway
 
Fruit Studios Ltd
First Floor
100 High Street
Winchester
Hampshire
SO23 9AH
 
T: 01962 809 103 
E: ben@fruitstudios.co.uk
W: www.fruitstudios.co.uk

====================================================

This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify Fruit Studios Ltd immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. Fruit Studios Ltd does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission. Opinions expressed in this email are those of Ben Callaway, and do not necessarily reflect those of Fruit Studios Ltd. If verification is required please request a hard-copy version.

====================================================

**Comment by shornuk** [comment]
Hi, 

It was intentional to leave not make html automatically associate with this package as it seems a little too opinionated to make it default for all html. That being said, if you do want this, it's pretty easy to do.  Go to your Packages > Craft-Twig and then hit settings. Then hit the "View Code" button, and you'll open the folder structure for the package. Go to grammers/craft-twig.cson and the first option is fileTypes. Just add HTML here and restart Atom. All HTML file should now be assigned the Craft-Twig syntax.  

![screenshot 2016-12-10 14 35 09](https://cloud.githubusercontent.com/assets/2061819/21074013/082c2974-bee6-11e6-82b9-39b6d28af4f3.png)

**Comment by jan-dh** [comment]
Is there any way to apply these settings only to files in the craft/templates folder?

**Comment by shornuk** [comment]
Not as far as I'm aware. I don't think they are detected on a folder level, rather an extension level. If you wanted to only detect particular folders, you could rename your html template files to use the .twig extension. Shoudl still work, and will only then select the Craft Twig syntax for those files.

**Comment by Moorst** [comment]
Had this problem myself and currently using https://atom.io/packages/atom-syntax and it seems to work pretty well. Just create a `.atomsyntaxrc` file in the root of the project with the following;

```
{
  "root": true,
  "syntaxes": {
    "*.html": "text.html.twig"
  }
}
```
