### ISSUE TITLE
Syntax highlighting breaks when escaping quotes

### ISSUE THREAD

**Issue by stevepiron** [fruitstudios/Craft-Twig#9]
Hello!

I've just encountered an issue with syntax highlighting: when escaping a single quote using a backslash (within a string wrapped in single quotes) the highlighting breaks.

![capture d ecran 2016-12-13 a 11 02 17](https://cloud.githubusercontent.com/assets/1664280/21135975/f331c82c-c123-11e6-83ea-65ee077755f8.png)

Maybe I'm doing it wrong and shouldn't be using the backslash, however the result is perfect on the front end. 🤔

**Comment by nfourtythree** [comment]
Hey @stevepiron 

Not sure if you will have been notified but have added a pull request that I believe should fix this. Here are my before and after screen shots

### Before
![Before](http://x.n43.me/0G3z0p2R0b0X/Image%202017-02-27%20at%208.33.01%20pm.png)

### After
![After](http://x.n43.me/3n1n1a1b2Q3q/Image%202017-02-27%20at%208.33.30%20pm.png)

Hopefully it will get folded in if it all looks ship shape 🚢

**Comment by stevepiron** [comment]
Very cool @nfourtythree!

Looking forward to seeing the update notification!

**Comment by stevepiron** [comment]
Thanks @shornuk! Don't forget to do whatever is necessary (if any) so that people with the package installed in Atom get the update notification
